---
title: "Naive_Bayes_2"
output: html_document
date: "2022-10-11"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Loading packages
library(e1071)
library(caTools)
library(caret)
library ("dplyr")
library('tibble')
library('readr')
library(tidyverse)
```

```{r}
mydata=read.csv("/Users/katherinemead/Documents/Urban_Institute_Files/Csv_files/school-districts_ccd_directory_2007.csv")

mydata[is.na(mydata)] = 0

# if migrant students > 0, migrant students = yes
small_df <- mydata %>% 
  mutate(migrant_yes_no = if_else(mydata$migrant_students > 0, "Yes", "No"))


# turn the following into factors: english_language_learners, enrollment, guidance_counselors_total_fte, instructional_aides_fte, lea_admin_support_staff_fte, lea_administrators_fte, librarian_specialists_fte, librarian_support_staff_fte, number_of_schools, other_staff_fte, school_admin_support_staff_fte, school_administrators_fte, school_counselors_fte, school_psychologists_fte, school_staff_total_fte, spec_ed_students, supervisory_union_number, support_staff_other_fte, support_staff_stu_wo_psych_fte, support_staff_students_fte, teachers_elementary_fte, teachers_kindergarten_fte, teachers_prek_fte, teachers_secondary_fte, teachers_total_fte, teachers_ungraded_fte

df <- mydata %>% 
    select(english_language_learners, enrollment, guidance_counselors_total_fte, instructional_aides_fte, lea_admin_support_staff_fte, lea_administrators_fte, librarian_specialists_fte, librarian_support_staff_fte, number_of_schools, other_staff_fte, school_admin_support_staff_fte, school_administrators_fte, school_counselors_fte, school_psychologists_fte, school_staff_total_fte, spec_ed_students, supervisory_union_number, support_staff_other_fte, support_staff_stu_wo_psych_fte, support_staff_students_fte, teachers_elementary_fte, teachers_kindergarten_fte, teachers_prek_fte, teachers_secondary_fte, teachers_total_fte, teachers_ungraded_fte)

#col_names <- names(df)
#df[,col_names] <- lapply(df[,col_names] , facto)

# replace NA with zero
df[is.na(df)] = 0

# just return a df with migrant students Y/N plus all the factors
df$migrantYN <- small_df$migrant_yes_no


names(df)[names(df) == "english_language_learners"] <- "English language learners"
names(df)[names(df) == "enrollment"] <- "Enrollment"
names(df)[names(df) == "guidance_counselors_total_fte"] <- "Guidance counselors"


ˆdf %>%
  rename(

    guidance_counselors_total_fte = "Guidance counselors", 
    instructional_aides_fte = "Instructional aides", 
    lea_admin_support_staff_fte = "Administrative staff (LEA)", 
    lea_administrators_fte = "Administrators (LEA)", 
    librarian_specialists_fte = "Librarian specialists", 
    librarian_support_staff_fte = "Librarian support staff", 
    number_of_schools = "Number of schools", 
    other_staff_fte = "Other staff", 
    school_admin_support_staff_fte = "School admin. support staff", 
    school_administrators_fte = "School administrators", 
    school_counselors_fte = "School counselors", 
    school_psychologists_fte = "School psychologists", 
    school_staff_total_fte = "Total school staff", 
    spec_ed_students = "Special education students", 
    supervisory_union_number = "Supervisory unions", 
    support_staff_other_fte = "Support staff (other)", 
    support_staff_stu_wo_psych_fte = "Support staff without psychologist", 
    support_staff_students_fte = "Support staff for students", 
    teachers_elementary_fte = "Elementary teachers", 
    teachers_kindergarten_fte = "Kindergarten teachers", 
    teachers_prek_fte = "pre-K teachers", 
    teachers_secondary_fte = "Secondary teachers", 
    teachers_total_fte = "Total teachers", 
    teachers_ungraded_fte = "Ungraded teachers"
    )

df

```

```{r}
# create a new df with averages for migrant Y/N for all the variables

migrant_enrollment <- mean(df[df$migrantYN == 'Yes', 'enrollment'])
non_migrant_enrollment <- mean(df[df$migrantYN == 'No', 'enrollment'])


columns <- names(df)
columns_tested <- columns[1:length(columns)-1]

#for all the columns except migrantYN

df_sum <- data.frame(matrix(ncol = 3, nrow = 0))
colnames(df_sum) <- c('Measure', 'Migrant Status', 'Average per 1000 students')

for (column in columns_tested){
  
  # create mini dataframe 1
  av_p_p_migrant <- round((mean(df[df$migrantYN == 'Yes', column])/migrant_enrollment)*1000, 0)
  migrant_status = "Yes"
  df_sum[nrow(df_sum) + 1,] = c(column, migrant_status, av_p_p_migrant)
  
  # create mini dataframe 2
  av_p_p_migrant <- round((mean(df[df$migrantYN == 'No', column])/non_migrant_enrollment)*1000, 0)
  migrant_status = "No"
  df_sum[nrow(df_sum) + 1,] = c(column, migrant_status, av_p_p_migrant)

}


df_sum <- df_sum[-c(3, 4, 19, 20, 51, 52), ]




```
```{r}
 # library
library(ggplot2)

measure <- df_sum$Measure

migrant_status <- df_sum$`Migrant Status` 
avg_per_1000 <- df_sum$`Average per 1000 students`
 
# Grouped
ggplot(df_sum, aes(fill=migrant_status, y=avg_per_1000, x=measure)) + coord_flip() +  
  ggtitle("Strategies for Using Homework Solution and Mini-Lecture Screencasts") +
    geom_bar(position="dodge", stat="identity")
```
```{r}
 # library
library(ggplot2)
 
# create a dataset
Measure <- c("Total teachers", "Total teachers", "English language learners", "English language learners", "Special education students", "Special education students", "School administrators", "School administrators")
Migrant_Students <- rep(c("Yes" , "No") , 4)
Number_per_1000_students <- c(57, 65, 62, 49, 103, 124, 3, 3)
data <- data.frame(measure, condition, value)
 
# Grouped
p <- ggplot(data, aes(fill=Migrant_Students, y=Number_per_1000_students, x=Measure)) + 
    geom_bar(position="dodge", stat="identity", width = 0.5) + theme(axis.text.x = element_text(angle = 10))
p + ggtitle("Comparison of Districts with and without Migrant Students") +
  xlab("Measure") + ylab("Number per 1000 students") + theme(text = element_text(size = 14))

```



```{r}
# Splitting data into train
# and test data

split <- sample.split(df, SplitRatio = 0.8)

train_cl <- subset(df, split == "TRUE")

test_cl <- subset(df, split == "FALSE")
 
# Feature Scaling

train_scale <- scale(train_cl[, 1:4])

test_scale <- scale(test_cl[, 1:4])
 
# Fitting Naive Bayes Model 
# to training dataset

set.seed(120)  # Setting Seed

classifier_cl <- naiveBayes(migrantYN ~ ., data = train_cl)
classifier_cl
 
# Predicting on test data'

y_pred <- predict(classifier_cl, newdata = test_cl)
 
# Confusion Matrix

cm <- table(test_cl$migrantYN, y_pred)
cm
 
# Model Evaluation
confusionMatrix(cm)

```

```{r}
table <- data.frame(cm)
table
```

```{r}
library(cvms)
library(tibble)   # tibble()

set.seed(1)
```


```{r}
y_pred <- predict(classifier_cl, newdata = test_cl)
 
# Confusion Matrix

cm <- table(test_cl$migrantYN, y_pred)

d_binomial <- tibble("target" = test_cl$migrantYN,
                     "prediction" = y_pred)

d_binomial

basic_table <- table(d_binomial)

cfm <- as_tibble(basic_table)

plot_confusion_matrix(cfm, 
                      target_col = "target", 
                      prediction_col = "prediction",
                      counts_col = "n")

```





